# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-06 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20170501_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 3, 58, 6, 389954, tzinfo=utc)),
        ),
    ]
